version: "3.3"

services:
    backend:
      image: gerrome/django-react_backend:1
    #  build:
    #      context: ./backend
      volumes:
        - .:/app
        - static_volume:/app/staticfiles/
      ports:
        - 8000:8000
      depends_on:
        - db

    db:
      image: postgres:11.17-alpine
      expose:
        - 5432      
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

    frontend:
      image: gerrome/django-react_frontend:1
    #  build:
    #      context: ./frontend
      ports:
        - 3000:3000
      volumes:
        - static_volume:/app/staticfiles/
      depends_on:
        - backend

    nginx:
      image: gerrome/django-react_nginx:1
    #  build:
    #      context: ./frontend
      ports:
        - 80:80
      depends_on:
        - frontend        
    
volumes:
   static_volume: 
