version: "3.8"

services:
    backend:
      build:
          context: ./backend
      volumes:
        - .:/app
        - static_volume:/app/staticfiles/
      expose:
        - 8000
      depends_on:
        - db

    db:
      image: postgres:10.1-alpine

    nginx:
      build:
          context: ./frontend
      ports:
        - 80:80
      volumes:
        - static_volume:/app/staticfiles/
      depends_on:
        - backend
    
volumes:
   static_volume: 
